### ISSUE TITLE
Repldex news checklist

### ISSUE THREAD

**Issue by Codemonkey51** [repldex/Repldex#15]
- [ ] #31
- [x] add reporter role
- [ ] setup repldex news db section 
- [ ] setup news article editing
- [ ] setup ui
- [ ] get some reporters (preferably already editor)

Tasks:
@Codemonkey51: code
@minx28: Get reporters

**Comment by Codemonkey51** [comment]
Repldex news is basically dead right now
